### ISSUE TITLE
为什么每次都要重绘所有路径？

### ISSUE THREAD

**Issue by CavanLife** [coolnameismy/demo#3]
在DrawRect 方法中，使用两层 for 循环遍历绘制，外层路径，内层 Point，这样造成的结果就是每次setNeedsDisplay 都绘制了之前所有的 path。会不会造成资源浪费啊

**Comment by coolnameismy** [comment]
会的。因为是demo，所以没有考虑那么多。在开发app时根据使用情况决定是否要优化
